//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLteMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAttachments
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdRequest { get; set; }
        public byte[] ByteContent { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> IdAttachmentType { get; set; }
    }
}
