//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrails
    {
        public int Id { get; set; }
        public string PerformedBy { get; set; }
        public System.DateTime Date { get; set; }
        public string Action { get; set; }
        public string ActionMessage { get; set; }
    }
}
