//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowSteps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlowSteps()
        {
            this.RequestHistories = new HashSet<RequestHistories>();
            this.Requests = new HashSet<Requests>();
        }
    
        public int Id { get; set; }
        public int IdEmployee { get; set; }
        public int StepNumber { get; set; }
        public string StepName { get; set; }
        public int IdFlowType { get; set; }
        public bool IsAttachmentNeed { get; set; }
        public bool IsMatrixNeeded { get; set; }
        public bool IsTransferNeed { get; set; }
        public bool IsSupervisorNeed { get; set; }
        public bool IsBuyersBlocker { get; set; }
        public Nullable<int> IdGroup { get; set; }
        public Nullable<int> IdAttachmentType { get; set; }
    
        public virtual AttachmentTypes AttachmentTypes { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual FlowTypes FlowTypes { get; set; }
        public virtual Groups Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHistories> RequestHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
