//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Attachments = new HashSet<Attachments>();
            this.RequestHistories = new HashSet<RequestHistories>();
        }
    
        public int Id { get; set; }
        public int IdTo { get; set; }
        public int IdFrom { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> RequestType_Id { get; set; }
        public int IdRequestor { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public int IdStatus { get; set; }
        public int IdFlowType { get; set; }
        public int IdFlowSteps { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> From_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments> Attachments { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Departments Departments1 { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual FlowSteps FlowSteps { get; set; }
        public virtual FlowTypes FlowTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHistories> RequestHistories { get; set; }
        public virtual RequestTypes RequestTypes { get; set; }
        public virtual Status Status { get; set; }
    }
}
